# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20150919_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followingtag',
            options={'verbose_name': 'FollowingTag', 'verbose_name_plural': 'FollowingTag'},
        ),
    ]
