# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-03 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_excerpt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
